/**
 * תווי Material Symbols שבשימוש · נקודות הקוד של הגופן
 * ש-expo-symbols טוען במלואו. בדפדפן נטענת רק תת-הקבוצה הזו.
 */
export const MATERIAL_GLYPH: Record<string, string> = {
  person: '\uE7FD',
  receipt_long: '\uEF6E',
  home: '\uE88A',
  logout: '\uE9BA',
  photo_camera: '\uE412',
  visibility: '\uE8F4',
  visibility_off: '\uE8F5',
  call: '\uE0B0',
  lock: '\uE897',
  add: '\uE145',
  remove: '\uE15B',
  face: '\uE87C',
  mood: '\uE7F2',
  psychology: '\uEA4A',
  notifications_active: '\uE7F7',
  location_on: '\uE0C8',
  send: '\uE163',
  shopping_cart: '\uE8CC',
  event: '\uE878',
  bar_chart: '\uE26B',
  close: '\uE5CD',
  chevron_right: '\uE5CC',
  chevron_left: '\uE5CB',
  expand_more: '\uE5CF',
  arrow_back: '\uE5C4',
  check: '\uE5CA',
  schedule: '\uE8B5',
  refresh: '\uE5D5',
  map: '\uE55B',
  download: '\uF090',
  description: '\uE873',
  inventory_2: '\uE1A1',
  login: '\uEA77',
  redeem: '\uE8B1',
  shopping_bag: '\uF1CC',
  calendar_month: '\uEBCC',
  edit: '\uE3C9',
  payments: '\uEF63',
  mail: '\uE158',
};
